### ISSUE TITLE
Unable to compile with R 4.5.2 and Rtools 4.5

### ISSUE THREAD

**Issue by bcmonsell** [tuckermcelroy/sigex#8]
I'm trying to install sigex with an updated version of R on my workstation, and I'm running into an issue with compiling C code.

There are a series of errors, but I suspect correcting the first one, where there's a version conflict with RcppArmadillo, will help with the other problems.

I get the following error:

C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo_bits/compiler_check.hpp:82:4: error: #error "*** C++14 compiler required; enable C++14 mode in your compiler, or use an earlier version of Armadillo"
   82 |   #error "*** C++14 compiler required; enable C++14 mode in your compiler, or use an earlier version of Armadillo"
      |    ^~~~~
In file included from C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo:501:
C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo_bits/fn_accu.hpp:27:1: error: 'accu' function uses 'auto' type specifier without trailing return type
   27 | auto
      | ^~~~
C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo_bits/fn_accu.hpp:27:1: note: deduced return type only available with '-std=c++14' or '-std=gnu++14'
C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo_bits/fn_accu.hpp:42:1: error: 'accu' function uses 'auto' type specifier without trailing return type
   42 | auto
      | ^~~~
C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo_bits/fn_accu.hpp:42:1: note: deduced return type only available with '-std=c++14' or '-std=gnu++14'
C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo_bits/fn_accu.hpp:57:1: error: 'accu' function uses 'auto' type specifier without trailing return type
   57 | auto
      | ^~~~
C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/library/RcppArmadillo/include/armadillo_bits/fn_accu.hpp:57:1: note: deduced return type only available with '-std=c++14' or '-std=gnu++14'
make: *** [C:/Users/monsell_b/AppData/Local/Programs/R/R-4.5.2/etc/x64/Makeconf:296: RcppExports.o] Error 1
ERROR: compilation failed for package 'sigex'
* removing 'C:/Users/MONSEL~1/AppData/Local/Temp/RtmpwjEovd/pkg-libdfc24d75bde/sigex'

Let me know if you need more information.
